/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 couch.gltf
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sofa-chair-0e8e009f398249b9bc13e8ff7078530a
Title: Sofa Chair
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/couch.gltf')
  return (
    <group {...props} dispose={null} scale={2.5} >
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} scale={[0.944, 1, 1]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.001']} scale={[0.934, 0.99, 0.99]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.001']} position={[0, 0.229, 0.039]} scale={[0.863, 1.02, 0.914]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.002']} position={[0, 0.017, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.material_0} position={[0.006, 0.678, -0.478]} rotation={[1.24, -0.013, -0.104]} scale={[0.4, 0.294, 0.354]} />
    </group>
  )
}

useGLTF.preload('/couch.gltf')
